[package]
name = "day03"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
divan = "0.1.21"

[[bench]]
name = "day-03-bench"
path = "benches/benchmarks.rs"
harness = false
